name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCpOdQTaDC2vc4qRPV3IxVTg
